name: tests and lint check

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make install
      - run: make lint
      - run: make test
      - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_ID }}
      with:
        coverageCommand: npm run coverage
        debug: true
